### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by dergigi** [lnproxy/lnproxy#1]
Make sure there is a proper LICENSE file in each and every repository.

- ❌ https://github.com/lnproxy/lnproxy - missing, but that's just a README for now
- ✅ https://github.com/lnproxy/lnproxy-relay (GPL-3.0)
- ✅ https://github.com/niteshbalusu11/lnproxy-ts (MIT)
- ❌ https://github.com/lnproxy/lnproxy-address - missing
- ❌ https://github.com/lnproxy/lnproxy-webui2 - missing
- ❌ https://github.com/lnproxy/lnproxy-spec - ⚠️ 404's for me?

**Comment by lnproxy** [comment]
Done, thanks!
